[package]
name = "Ising2D"
version = "0.1.0"
authors = ["chae.yeun.park"]
edition = "2018"

[dependencies]
rand = "0.8"
itertools = "0.10"
itertools-num = "*"
nalgebra = "0.30.1"
rayon = "1.5"
#scoped_threadpool = "0.1.9"
serde = "*"
serde-pickle = "*"
